---
title: "SVR_Regression"
output: html_document
---

##SVR

##Importing the Dataset
```{r}

getwd()
setwd("/Users/dana/Spyder/Gits/Machine-Learning-A-Z/SVR")
dataset = read.csv("Position_Salaries.csv")
dataset = dataset[2:3]

```

##splitting the dataset into training set and test set
```{r}

# library(caTools)
# set.seed(123)
# split = sample.split(dataset$Salary, SplitRatio = 2/3)
# training_set = subset(dataset, split == TRUE)
# test_set = subset(dataset, split == FALSE)

```

##Feature Scaling
```{r}

# training_set = scale(training_set)
# test_set = scale(test_set)

```

##Fitting SVR to the dataset
```{r}
##create your regressor here, may look like this:
# dataset$Level2 = dataset$Level^2
# dataset$Level3 = dataset$Level^3
# dataset$Level4 = dataset$Level^4
# regressor = lm(formula = Salary ~ .,
#               data = dataset)

library(e1071)
regressor = svm(formula = Salary ~ .
                , data = dataset
                , type = "eps-regression")

#eps-regression for svr model, c-classification for svm model

```

##Predicting a new result with SVR
```{r}

y_pred = predict(regressor, data.frame(Level=6.5))
                                      
                                       # ,Level2=6.5^2
                                       # ,Level3=6.5^3
                                       # ,Level4=6.5^4))

```

##Visualizing the SVR results
```{r}

library(ggplot2)
ggplot() +
  geom_point(aes(x = dataset$Level, y = dataset$Salary),
             colour ='red') +
  geom_line(aes(dataset$Level, y = predict(regressor, newdata = dataset)),
            colour = 'blue') +
  ggtitle('Truth or Bluff (SVR)') +
  xlab('Level') +
  ylab('Salary')

```

##Visualizing the SVR results with a smooth curve // higher resolution
```{r}

library(ggplot2)
x_grid = seq(min(dataset$Level),max(dataset$Level),0.1)
ggplot() +
  geom_point(aes(x = dataset$Level, y = dataset$Salary),
             colour ='red') +
  geom_line(aes(x_grid, y = predict(regressor, newdata = data.frame(Level = x_grid))),
            colour = 'blue') +
  ggtitle('Truth or Bluff (SVR)') +
  xlab('Level') +
  ylab('Salary')

```