#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Feb 18 20:02:09 2017

@author: dana
"""

##simple linear regression
"""OLS:
   sum (y - y^)^2 -> min
   best fit line = the line that minimizes the sum of the squares
   """

##Set working directory
os.getcwd()
os.chdir('/Users/Dana/Spyder/Gits/Machine-Learning-A-Z/Simple_Linear_Regression')

a