---
title: "Random_Forests"
output: html_document
---

##Regression Template

##Importing the Dataset 
```{r}
 
getwd() 
setwd("/Users/dana/Spyder/Gits/Machine-Learning-A-Z/Random_Forest_Regression")
dataset = read.csv("Position_Salaries.csv")
dataset = dataset[2:3]

```

##splitting the dataset into training set and test set
```{r}

# library(caTools)
# set.seed(123)
# split = sample.split(dataset$Salary, SplitRatio = 2/3)
# training_set = subset(dataset, split == TRUE)
# test_set = subset(dataset, split == FALSE)

```

##Feature Scaling
```{r}

# training_set = scale(training_set)
# test_set = scale(test_set)

```

##Fitting Random Forest regresssion model to the dataset
```{r}
##create your regressor here, may look like this:
# dataset$Level2 = dataset$Level^2
# dataset$Level3 = dataset$Level^3
# dataset$Level4 = dataset$Level^4
# regressor = lm(formula = Salary ~ .,
#               data = dataset)

library(randomForest)
set.seed(1234)
regressor = randomForest(x = dataset[1]
                       , y = dataset$Salary
                       , ntree = 500)

##dataset[1] gives a sub set dataframe
##dataset$Salary gives a vector
```

##Predicting a new result with Random Forest regression
```{r}

y_pred = predict(regressor, data.frame(Level=6.5))

```

##Visualizing the results with a smooth curve // higher resolution
```{r}

library(ggplot2)
x_grid = seq(min(dataset$Level),max(dataset$Level),0.1)
ggplot() +
  geom_point(aes(x = dataset$Level, y = dataset$Salary),
             colour ='red') +
  geom_line(aes(x_grid, y = predict(regressor, newdata = data.frame(Level = x_grid))),
            colour = 'blue') +
  ggtitle('Truth or Bluff (Random Forest Regression Model)') +
  xlab('Level') +
  ylab('Salary')

```
